const {chromium}=require('playwright'),assert=require('node:assert/strict'),{createServer}=require('../server.cjs'),path=require('node:path');
(async()=>{const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const origin='http://127.0.0.1:'+server.address().port;
 await page.goto(origin+'/#maps');await page.locator('#map-inner svg').waitFor();await page.locator('#advanced-map-filters summary').click();
 await page.locator('.map-layer[data-id=containers]').check();await page.locator('.map-marker.container').first().waitFor();assert.ok(await page.locator('.map-marker.container').count()>100);await page.locator('.map-layer[data-id=loot]').check();await page.locator('.map-marker.loot').first().waitFor();assert.ok(await page.locator('.map-marker.loot').count()>100);await page.locator('.map-layer[data-id=keys]').check();await page.locator('.map-marker.lock').first().waitFor();
 await page.locator('[data-advanced=hide-containers]').click();await page.waitForFunction(()=>document.querySelector('#loot-layer-status')?.textContent.includes('Containers: 0 shown'));assert.equal(await page.locator('.map-marker.container').count(),0);await page.locator('[data-advanced=show-containers]').click();await page.locator('.map-marker.container').first().waitFor();
 await page.locator('#loot-search').fill('no-such-item-zzzz');await page.waitForFunction(()=>document.querySelector('#loot-layer-status')?.textContent.includes('Loose loot: 0 shown'));await page.locator('[data-advanced=reset-map-filters]').click();await page.locator('.map-marker.loot').first().waitFor();assert.equal(await page.locator('#loot-search').inputValue(),'');
 const id=await page.locator('#loot-item-add option').nth(1).getAttribute('value');await page.locator('#loot-item-add').selectOption(id);await page.locator('.filter-chips button').waitFor();assert.ok(await page.evaluate(()=>profile().mapPresets.customs.layers.loot));
 await page.locator('[data-container-type]').first().uncheck();const hidden=await page.evaluate(()=>AdvancedUI.filters().hiddenContainers[0]);await page.locator('#map-select').selectOption('woods');assert.equal(await page.evaluate(()=>AdvancedUI.filters().hiddenContainers.includes('Toolbox')),false);
 await page.locator('#map-select').selectOption('customs');assert.equal(await page.evaluate(name=>AdvancedUI.filters().hiddenContainers.includes(name),hidden),true);await page.locator('[data-feature=map-preset-save]').click();assert.equal(await page.evaluate(name=>AdvancedUI.filters().hiddenContainers.includes(name),hidden),true);await page.reload();await page.locator('.filter-chips button').waitFor();assert.ok(await page.evaluate(()=>mapLayers.loot));await page.locator('.map-marker.loot').first().waitFor();await page.locator('.map-marker.lock').first().waitFor();await page.screenshot({path:path.join(__dirname,'../evidence/map-loot-filters.png'),fullPage:true});
 await page.goto(origin+'/?overlay=1#maps');await page.locator('.map-marker.container').first().waitFor();await page.locator('.map-marker.loot').first().waitFor();await page.locator('.map-marker.lock').first().waitFor();assert.deepEqual(errors,[]);
 await page.goto(origin+'/#hideout');await page.locator('.station-tile').first().click();assert.equal(await page.evaluate(()=>document.activeElement.classList.contains('hideout-level')),true);await page.locator('[data-bitcoin=hours]').fill('12');await page.locator('[data-bitcoin=hours]').press('Tab');await page.locator('[data-bitcoin=sale]').fill('500000');await page.locator('[data-bitcoin=sale]').press('Tab');assert.match(await page.locator('.bitcoin-plan').textContent(),/1,000,000/);
 await page.goto(origin+'/#market');await page.evaluate(()=>{const i=data.items.find(i=>i.lastLowPrice>0);profile().watchlist=[i.id];selectedItem=i.id;save();render();});await page.locator('.quote-history').waitFor();await page.reload();await page.evaluate(()=>{selectedItem=profile().watchlist[0];render();});assert.match(await page.locator('.quote-history').textContent(),/1 community snapshots/);
 await page.screenshot({path:path.join(__dirname,'../evidence/advanced-history.png')});assert.deepEqual(errors,[]);console.log('PASS: per-map container/item filters, enabled-layer restart, clickable stations, manual Bitcoin estimate and deduplicated price history.');
 }finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
