const {test}=require('node:test'),assert=require('node:assert/strict'),{proximity,exitState,mapToWorld,exitKey,spawnKind,spriteName}=require('../map-logic.cjs'),{worldToMap}=require('../core.cjs'),fs=require('node:fs'),path=require('node:path');
const exit={kind:'extract',id:'e1',name:'Gate',faction:'pmc',position:{x:0,y:2,z:0},outline:[{x:-5,z:-5},{x:5,z:-5},{x:5,z:5},{x:-5,z:5}],bottom:0,top:4};
test('extract proximity measures region edge and rejects another floor',()=>{assert.equal(proximity({x:0,y:2,z:0},exit).distance,0);assert.equal(proximity({x:30,y:2,z:0},exit).nearby,true);assert.equal(proximity({x:31,y:2,z:0},exit).nearby,false);assert.equal(proximity({x:0,y:30,z:0},exit).nearby,false);assert.equal(proximity(null,exit).nearby,false);});
test('nearby is not availability, blocked factions and unavailable checks never glow green',()=>{const player={x:0,y:2,z:0},unknown=exitState(exit,{player});assert.equal(unknown.highlight,true);assert.equal(unknown.available,false);assert.equal(exitState(exit,{player,role:'scav',manual:'available'}).highlight,false);assert.equal(exitState(exit,{player,manual:'unavailable'}).highlight,false);assert.equal(exitState(exit,{player,manual:'available'}).available,true);assert.equal(exitState(exit,{player:{x:0,z:0}}).levelKnown,false);});
test('point-based transit checks have height tolerance',()=>{const transit={kind:'transit',position:{x:100,y:5,z:100}};assert.equal(exitState(transit,{player:{x:100,y:5,z:110},role:'scav'}).highlight,true);assert.equal(exitState(transit,{player:{x:100,y:50,z:110}}).highlight,false);});
test('manual map point inversion preserves world coordinates for all calibrated maps',()=>{const configs=JSON.parse(fs.readFileSync(path.join(__dirname,'../reference/Config/maps.json'),'utf8'));for(const config of Object.values(configs)){const target={x:13.4,z:-29.2},normalized=worldToMap(target,config),result=mapToWorld(normalized,config,worldToMap);assert.ok(Math.abs(result.x-target.x)<1e-7);assert.ok(Math.abs(result.z-target.z)<1e-7);}});
test('exit checks are isolated by mode, source map variant, kind and faction',()=>{assert.notEqual(exitKey('regular','Factory','extract',exit),exitKey('pve','Factory','extract',exit));assert.notEqual(exitKey('regular','Factory','extract',exit),exitKey('regular','Night Factory','extract',exit));assert.notEqual(exitKey('regular','Factory','extract',exit),exitKey('regular','Factory','extract',{...exit,faction:'scav'}));});
test('all-side and mixed starts remain shared rather than falsely labeled PMC',()=>{assert.equal(spawnKind(['all']),'shared');assert.equal(spawnKind(['pmc','scav']),'shared');assert.equal(spawnKind(['usec','bear']),'pmc');assert.equal(spawnKind(['scav']),'scav');assert.equal(spawnKind([]),'unknown');});
test('newer named bosses, event variants and guards resolve to their own custom portraits',()=>{assert.equal(spriteName('The Wedge (Labs)'),'wedge-labs');assert.equal(spriteName('Shadow of Tagilla'),'shadow-tagilla');assert.equal(spriteName('Big Pipe'),'big-pipe');assert.equal(spriteName('Glukhar Guard Security'),'glukhar-guard');assert.equal(spriteName('Gus'),'gus');});
