const {_electron:electron}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const directory=path.join(__dirname,'../evidence/minimap-test-user-data');const executablePath=path.join(__dirname,'../node_modules/electron/dist/electron.exe');
async function launch(){return electron.launch({executablePath,args:[path.join(__dirname,'..')],env:{...process.env,TC_TEST_USER_DATA:directory}});}
(async()=>{let app;try{
 app=await launch();const main=await app.firstWindow(),errors=[];main.on('pageerror',e=>errors.push(e.message));await main.locator('h1').waitFor();await main.goto((await main.url()).split('#')[0]+'#settings');await main.locator('[data-hotkey=overlay]').waitFor();
 const conflict=await main.evaluate(()=>window.desktop.saveShortcuts({overlay:'CommandOrControl+Alt+F10',lock:'CommandOrControl+Alt+F10',scan:'not-a-key'}));assert.equal(conflict.status.lock,'Duplicate');assert.equal(conflict.status.scan,'Invalid shortcut');await main.evaluate(()=>window.desktop.saveShortcuts({}));
 await main.evaluate(()=>{profile().location={map:profile().map,nx:.5,ny:.5,source:'Synthetic offline test position',at:Date.now()};state.settings.minimapFollow=true;state.settings.minimapZoom=3;save();});const added=app.waitForEvent('window');await main.locator('#overlay-button').click();const mini=await added;mini.on('pageerror',e=>errors.push(e.message));await mini.locator('#map-inner svg').waitFor();await mini.locator('.minimap-readout').waitFor();assert.equal(await mini.locator('.page-heading').count(),0);assert.match(await mini.locator('.position-age').textContent(),/POSITION/);
 await mini.evaluate(()=>window.desktop.resizeOverlay({width:500,height:510}));await mini.waitForFunction(()=>window.innerWidth===500);assert.ok(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('overlay=1')).isAlwaysOnTop()));
 const stage=await mini.locator('#map-stage').boundingBox();assert.ok(stage.height>250);assert.ok(stage.y+stage.height<510);const grip=await mini.locator('.resize-grip').boundingBox();await mini.mouse.move(grip.x+grip.width-4,grip.y+grip.height-4);await mini.mouse.down();await new Promise(r=>setTimeout(r,100));await mini.mouse.move(grip.x+grip.width+26,grip.y+grip.height+26);await mini.mouse.up();await mini.waitForFunction(()=>innerWidth>500);await mini.evaluate(()=>window.desktop.resizeOverlay({width:500,height:510}));await mini.waitForFunction(()=>innerWidth===500);
 const old=await mini.locator('#map-inner').evaluate(e=>e.style.transform);await mini.keyboard.press('+');assert.notEqual(await mini.locator('#map-inner').evaluate(e=>e.style.transform),old);
 await mini.locator('[data-tool=follow]').click();assert.equal(await mini.locator('[data-tool=follow]').getAttribute('aria-pressed'),'false');
 await mini.evaluate(()=>window.desktop.lockOverlay());await mini.waitForFunction(()=>document.body.classList.contains('overlay-locked'));assert.match(await mini.locator('.overlay-lock-status').textContent(),/TO UNLOCK/);await mini.evaluate(()=>window.desktop.lockOverlay());
 await mini.evaluate(()=>document.querySelector('#toast').classList.remove('visible'));await mini.screenshot({path:path.join(__dirname,'../evidence/minimap-desktop.png')});await main.goto((await main.url()).split('#')[0]+'#overview');await main.locator('h1').waitFor();await main.screenshot({path:path.join(__dirname,'../evidence/overview-background.png')});
 await main.keyboard.press('Control+,');await main.locator('[data-hotkey=overlay]').waitFor();await main.locator('#profile-name').focus();await main.keyboard.press('c');assert.match(await main.locator('#profile-name').inputValue(),/c/);await main.locator('h1').click();await main.keyboard.press('?');await main.locator('#shortcut-help').waitFor();await main.keyboard.press('Escape');assert.equal(await main.locator('#shortcut-help').evaluate(e=>e.open),false);
 assert.deepEqual(errors,[]);await mini.evaluate(()=>window.desktop.resizeOverlay({width:510,height:520}));await main.evaluate(()=>close());await app.close();app=null;
 const saved=JSON.parse(fs.readFileSync(path.join(directory,'desktop-preferences.json'),'utf8'));assert.equal(saved.bounds.width,510);assert.equal(saved.bounds.height,520);
 app=await launch();const restored=await app.firstWindow();await restored.locator('h1').waitFor();const opened=app.waitForEvent('window');await restored.locator('#overlay-button').click();const again=await opened;await again.locator('#map-inner svg').waitFor();assert.equal(await again.evaluate(()=>innerWidth),510);assert.equal((await again.evaluate(()=>window.desktop.overlayStatus())).locked,false);assert.equal(await again.locator('[data-tool=follow]').getAttribute('aria-pressed'),'false');const centered=await again.evaluate(()=>{const inner=document.querySelector('#map-inner').getBoundingClientRect(),stage=document.querySelector('#map-stage').getBoundingClientRect();return Math.abs(inner.x+inner.width*.5-stage.x-stage.width*.5)<2&&Math.abs(inner.y+inner.height*.5-stage.y-stage.height*.5)<2;});assert.ok(centered,'Opening in free-pan mode centers saved position');
 console.log('PASS: native minimap dimensions/topmost, resize/persistence/restart, lock recovery, shortcut conflicts, local keyboard controls, typing guards, main background and minimap previews.');
 }finally{await app?.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
