const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {createServer}=require('../server.cjs');
(async()=>{const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;let browser;try{
 browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);await page.locator('h1').waitFor();assert.match(await page.locator('h1').textContent(),/next raid/);
 await page.goto(origin+'/#quests');await page.locator('#quest-filter').selectOption('available');assert.ok(await page.locator('.task-card').count()>0);const first=page.locator('.task-card').first(),id=await first.locator('.task-status').getAttribute('data-id');await first.locator('.task-status').selectOption('active');await page.locator('#quest-filter').selectOption('active');assert.ok(await page.locator('.task-card').count()>0);await page.locator('.task-card').first().locator('[data-action=pin]').click();await page.reload();await page.locator('h1').waitFor();const saved=JSON.parse(await page.evaluate(()=>localStorage.getItem('tc-state-v1')));assert.equal(saved.profiles[0].tasks[id],'active');assert.ok(saved.profiles[0].pinned.includes(id));
 await page.goto(origin+'/#maps');await page.locator('#map-inner svg').waitFor();await page.locator('#position-input').fill('163, 5, -35');await page.locator('[data-action=position-apply]').click();await page.locator('.map-marker.player').waitFor();assert.ok(await page.locator('.map-marker.extract').count()>0);await page.locator('#map-select').selectOption('labyrinth');await page.locator('#map-inner svg').waitFor();
 await page.goto(origin+'/#hideout');await page.locator('.hideout-level').first().selectOption('1');assert.ok(await page.locator('.badge').first().textContent());await page.goto(origin+'/#shopping');assert.ok(await page.locator('.owned-count').count()>0);await page.locator('.owned-count').first().fill('2');await page.locator('.owned-count').first().dispatchEvent('change');
 await page.goto(origin+'/#market');await page.locator('#search').fill('Salewa');await page.locator('.item-row').first().waitFor();assert.match(await page.locator('.item-row').first().textContent(),/Salewa/);await page.locator('.item-row').first().locator('[data-action=watch]').click();await page.locator('.item-row').first().locator('[data-action=item-detail]').click();await page.locator('[data-action=cultist-add]').click();await page.goto(origin+'/#cultist');await page.locator('.slot-value').first().waitFor();assert.ok(Number(await page.locator('.slot-value').first().inputValue())>0);await page.locator('[data-action=circle-start]').click();assert.match(await page.locator('#circle-countdown').textContent(),/h/);
 await page.goto(origin+'/#journal');await page.locator('#raid-notes').fill('UI smoke test');await page.locator('[data-action=raid-save]').click();assert.match(await page.locator('.journal-entry').textContent(),/UI smoke test/);await page.goto(origin+'/#ammo');await page.locator('#search').fill('M855');assert.ok(await page.locator('.row').count()>0);
 await page.goto(origin+'/#settings');await page.locator('#profile-mode').selectOption('pve');await page.locator('[data-action=profile-save]').click();await page.waitForFunction(()=>document.querySelector('#data-status').textContent.includes('pve'));await page.goto(origin);await page.locator('h1').waitFor();fs.mkdirSync(path.join(__dirname,'../evidence'),{recursive:true});await page.screenshot({path:path.join(__dirname,'../evidence/overview.png'),fullPage:true});await page.goto(origin+'/#maps');await page.locator('#map-inner svg').waitFor();await page.screenshot({path:path.join(__dirname,'../evidence/maps.png'),fullPage:true});await page.setViewportSize({width:650,height:760});await page.goto(origin+'/?overlay=1#maps');await page.locator('#map-inner svg').waitFor();await page.screenshot({path:path.join(__dirname,'../evidence/overlay.png'),fullPage:true});
 assert.deepEqual(errors,[]);console.log('PASS: quest status and pins persist; map imports and assets; hideout and inventory; flea search/watchlist; sacrifice plan and timer; journal; ammo; PvE data; overlay layout.');
 }finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
