'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'../..'),appRoot=path.join(root,'companion'),version=require('../package.json').version;
if(process.platform!=='win32'||process.arch!=='x64')throw Error('Build on Windows x64 with the installed Electron runtime.');
const commit=cp.execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),out=path.join(appRoot,'evidence',`release-${version}-${commit.slice(0,7)}`),folder=path.join(out,`TarkovCompanion-${version}-win-x64`),destination=path.join(folder,'resources/app');
if(fs.existsSync(folder))throw Error('Release staging already exists; use a fresh commit or inspect the existing build.');
fs.mkdirSync(out,{recursive:true});fs.cpSync(path.join(appRoot,'node_modules/electron/dist'),folder,{recursive:true});fs.renameSync(path.join(folder,'electron.exe'),path.join(folder,'TarkovCompanion.exe'));fs.rmSync(path.join(folder,'resources/default_app.asar'),{force:true});
const files=cp.execFileSync('git',['ls-tree','-r','--name-only',commit,'companion'],{cwd:root,encoding:'utf8'}).trim().split(/\r?\n/).filter(f=>!/^companion\/(tests|evidence|reference|art\/references|maps\/interactive)\//.test(f)&&!f.endsWith('.cmd')&&!f.endsWith('/spawn_boss.png'));
for(const name of files){const target=path.join(destination,name.slice('companion/'.length));fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,cp.execFileSync('git',['show',commit+':'+name],{cwd:root,maxBuffer:100*1024*1024}));}
cp.execFileSync('npm.cmd',['ci','--omit=dev','--ignore-scripts','--no-audit','--no-fund'],{cwd:destination,stdio:'inherit',shell:true});
const forbidden=['state.json','settings.json','tracker-state.json','desktop-preferences.json','log-cursors.json','sync-inbox.json'];
function audit(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);if(entry.isDirectory()){if(['local-backups','.git','evidence'].includes(entry.name))throw Error('Private/build directory in package: '+entry.name);audit(file);}else if(forbidden.includes(entry.name)||/\.(?:log|traineddata)$/i.test(entry.name))throw Error('Personal/generated file in package: '+entry.name);}}
audit(folder);
const licenseFolder=path.join(folder,'licenses');fs.mkdirSync(path.join(licenseFolder,'maps'),{recursive:true});for(const name of ['LICENSE.md','README.md'])fs.copyFileSync(path.join(appRoot,'licenses/maps',name),path.join(licenseFolder,'maps',name));
const production=[];function inventory(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(!e.isDirectory())continue;const at=path.join(dir,e.name),pkg=path.join(at,'package.json');if(fs.existsSync(pkg)){const p=JSON.parse(fs.readFileSync(pkg));production.push({name:p.name,version:p.version,license:p.license||null,path:path.relative(folder,at)});}if(e.name.startsWith('@')||e.name==='node_modules')inventory(at);if(fs.existsSync(path.join(at,'node_modules')))inventory(path.join(at,'node_modules'));}}inventory(path.join(destination,'node_modules'));fs.writeFileSync(path.join(licenseFolder,'production-dependencies.json'),JSON.stringify(production,null,2)+'\n');fs.copyFileSync(path.join(destination,'THIRD-PARTY-NOTICES.md'),path.join(folder,'THIRD-PARTY-NOTICES.md'));
const meta={version,commit,electron:require('../node_modules/electron/package.json').version,platform:'win32-x64',builtUtc:new Date().toISOString()};fs.writeFileSync(path.join(folder,'BUILD.json'),JSON.stringify(meta,null,2)+'\n');
fs.writeFileSync(path.join(folder,'START-HERE.txt'),`Tarkov Companion ${version} - Windows x64 preview\r\n\r\nExtract the entire ZIP to a writable folder, then open TarkovCompanion.exe.\r\nNo Node.js or installer is required. Keep all files together.\r\nProgress is stored in %APPDATA%\\TarkovCompanion, outside this folder.\r\nUse Sync to detect supported local sources and refresh community data.\r\nHideout levels/inventory are manual; real quest/raid log sync is unverified.\r\nUse borderless or a second display for overlays; exclusive fullscreen is not guaranteed.\r\nThis unsigned preview is unofficial, not affiliated with or approved by BSG.\r\nOptional OCR downloads its English model on first use.\r\nSource, docs and issue reports: https://github.com/exe-create/TarkovCompanion\r\nThird-party runtime licenses are included; see resources/app/README.md for data sources.\r\n`);
const zip=folder+'.zip',quote=s=>"'"+s.replaceAll("'","''")+"'";cp.execFileSync('powershell.exe',['-NoProfile','-Command',`Compress-Archive -LiteralPath ${quote(folder)} -DestinationPath ${quote(zip)} -CompressionLevel Optimal`],{stdio:'inherit'});
const digest=crypto.createHash('sha256').update(fs.readFileSync(zip)).digest('hex');fs.writeFileSync(path.join(out,'SHA256SUMS.txt'),`${digest}  ${path.basename(zip)}\n`);fs.writeFileSync(path.join(out,'release-build.json'),JSON.stringify({...meta,folder,zip,sha256:digest,bytes:fs.statSync(zip).size},null,2));console.log(JSON.stringify({folder,zip,sha256:digest,bytes:fs.statSync(zip).size}));
