const fs=require('node:fs'),path=require('node:path');
async function get(endpoint,mode){const r=await fetch(`https://json.tarkov.dev/${mode}/${endpoint}`,{signal:AbortSignal.timeout(45000)});if(!r.ok)throw Error(`${endpoint}: data service returned ${r.status}`);const j=await r.json();if(!j.data)throw Error(`${endpoint}: invalid response`);return j.data;}
async function sync(mode='regular'){
 if(!['regular','pve','pvp-season'].includes(mode))throw Error('Unsupported game mode');
 const endpoints=['items','tasks','hideout','maps','traders'];const responses=await Promise.all(endpoints.map(async e=>{const [raw,language]=await Promise.all([get(e,mode),get(e+'_en',mode)]);return{raw,language};}));
 const [crafts,barters]=await Promise.all([get('crafts',mode),get('barters',mode)]);
 const [ir,tr,hr,mr,vr]=responses;const itemRaw=ir.raw.items,mapRaw=mr.raw.maps,traderRaw=vr.raw;
 if(!itemRaw||!tr.raw.tasks||!Object.keys(hr.raw).length)throw Error('Incomplete response; existing cache preserved');
 const word=(key,dict,fallback)=>dict[key]||fallback||key;
 const itemName=id=>word(itemRaw[id]?.name,ir.language,itemRaw[id]?.normalizedName?.replace(/-/g,' ')||id);
 const mapName=id=>word(mapRaw[id]?.name,mr.language,mapRaw[id]?.normalizedName?.replace(/-/g,' ')||'Any location');
 const traderName=id=>word(traderRaw[id]?.name,vr.language,traderRaw[id]?.normalizedName||id);
 const questItems=Object.fromEntries(Object.entries(tr.raw.questItems||{}).map(([id,q])=>[id,{...q,name:word(q.name,tr.language,id),shortName:word(q.shortName,tr.language,id)}]));
 const items=Object.values(itemRaw).map(i=>({...i,id:i.id,name:itemName(i.id),shortName:word(i.shortName,ir.language,itemName(i.id)),iconLink:i.iconLink,basePrice:i.basePrice,avg24hPrice:i.avg24hPrice,lastLowPrice:i.lastLowPrice,low24hPrice:i.low24hPrice,high24hPrice:i.high24hPrice,changeLast48hPercent:i.changeLast48hPercent,updated:i.updated,width:i.width,height:i.height,properties:i.properties,types:i.types,link:i.link,buyFor:(i.buyFromTrader||i.buyFor||[]).map(s=>({...s,vendor:{id:s.trader,name:traderName(s.trader||s.vendor?.id||s.source)}})),sellFor:(i.sellToTrader||i.sellFor||[]).map(s=>({...s,vendor:{id:s.trader,name:traderName(s.trader||s.vendor?.id||s.source)},priceRUB:s.priceRUB}))}));
 const tasks=Object.values(tr.raw.tasks).map(t=>({...t,name:word(t.name,tr.language,t.normalizedName?.replace(/-/g,' ')),traderId:t.trader,trader:traderName(t.trader),neededKeys:(t.neededKeys||[]).map(k=>({...k,mapName:mapName(k.map)})),map:t.map?mapName(t.map):'Any location',requirements:(t.taskRequirements||[]).map(r=>({id:r.task,status:r.status})),objectives:(t.objectives||[]).map(o=>({...o,description:word(o.description,tr.language,'Objective description unavailable'),itemId:o.items?.[0]||o.item||o.questItem,itemName:o.questItem?questItems[o.questItem]?.name:(o.items||[o.item]).filter(Boolean).slice(0,5).map(itemName).join(' / '),questInventory:!!o.questItem,count:o.count??(o.questItem?1:null),maps:(o.maps||[]).map(mapName)}))}));
 const hideout=Object.values(hr.raw).map(s=>({id:s.id,name:word(s.name,hr.language,s.normalizedName.replace(/-/g,' ')),description:'Current community requirements',levels:s.levels.map(l=>({level:l.level,constructionTime:l.constructionTime,bonuses:(l.bonuses||[]).map(b=>({...b,name:word(b.name,hr.language,b.type||'Bonus')})),requirements:[...(l.itemRequirements||[]).map(r=>({type:'item',name:itemName(r.item),itemId:r.item,quantity:r.count,foundInRaid:!!r.attributes?.foundInRaid})),...(l.stationLevelRequirements||[]).map(r=>({type:'module',name:word(hr.raw[r.station]?.name,hr.language,r.station),quantity:r.level})),...(l.traderRequirements||[]).map(r=>({type:'trader',name:traderName(r.trader),quantity:r.level})),...(l.skillRequirements||[]).map(r=>({type:'skill',name:word(r.skill,hr.language,r.skill),quantity:r.level}))]}))}));
 const questMarkers={};for(const t of tasks)for(const o of t.objectives)for(const z of o.zones||[]){const map=mapRaw[z.map];if(!map||!z.position)continue;let slug=map.normalizedName.replace(/-/g,'').replace('thelab','lab');if(slug==='groundzero21+')slug='groundzero';const arr=questMarkers[slug]||(questMarkers[slug]=[]);arr.push({quest:t.name,questId:t.id,objectiveId:o.id,description:o.description,...z.position});}
 const extracts=Object.values(mapRaw).map(m=>({name:mapName(m.id),extracts:(m.extracts||[]).map(e=>({...e,name:word(e.name,mr.language,e.name)}))}));
 const mobName=id=>word(mr.raw.mobs?.[id]?.name,mr.language,mr.raw.mobs?.[id]?.normalizedName?.replace(/-/g,' ')||id);
 const mapKey=m=>{const n=m.normalizedName.replace(/-/g,'');if(n.includes('factory'))return'factory';if(n.startsWith('groundzero'))return'groundzero';if(n.startsWith('thelabyrinth'))return'labyrinth';if(n.startsWith('thelab'))return'lab';return n;};
 const mapIntel=Object.values(mapRaw).map(m=>({id:m.id,name:mapName(m.id),mapKey:mapKey(m),raidDuration:m.raidDuration,extracts:extracts.find(g=>g.name===mapName(m.id))?.extracts||[],
   transits:(m.transits||[]).map(t=>({...t,destination:mapName(t.map),description:word(t.description,mr.language,'Transit'),conditions:t.conditions?word(t.conditions,mr.language,t.conditions):null})),
   lootLoose:m.lootLoose||[],lootContainers:(m.lootContainers||[]).map(c=>({...c,name:word(mr.raw.lootContainers?.[c.lootContainer]?.name,mr.language,'Container')})),locks:m.locks||[],switches:(m.switches||[]).map(s=>({...s,name:word(s.name,mr.language,'Switch')})),btrStops:m.btrStops||[],cardinalRotation:m.coordinateToCardinalRotation,spawns:(m.spawns||[]).filter(s=>s.position),hazards:(m.hazards||[]).map(h=>({...h,name:word(h.name,mr.language,h.hazardType)})),
   bosses:(m.bosses||[]).map(b=>({id:b.mob,name:mobName(b.mob),portrait:mr.raw.mobs?.[b.mob]?.imagePortraitLink,spawnChance:b.spawnChance,spawnTime:b.spawnTime,spawnTrigger:b.spawnTrigger,escorts:(b.escorts||[]).map(e=>({id:e.mob,name:mobName(e.mob),portrait:mr.raw.mobs?.[e.mob]?.imagePortraitLink})),locations:(b.spawnLocations||[]).map(l=>{let points=l.positions||[];if(!points.length)points=(m.spawns||[]).filter(s=>s.zoneName===(l.spawnKey||l.name)&&s.categories?.some(c=>['boss','all','bot'].includes(c))).map(s=>s.position);return{name:word(l.name,mr.language,l.name),position:points.length?{x:points.reduce((n,p)=>n+p.x,0)/points.length,y:points.reduce((n,p)=>n+p.y,0)/points.length,z:points.reduce((n,p)=>n+p.z,0)/points.length}:null,chance:l.chance};})}))}));
 const result={meta:{updatedUtc:new Date().toISOString(),source:'tarkov.dev community JSON API',gameMode:mode,fresh:true,gamePatchChecked:'1.2.0.0',geometrySource:'Original tracker reference / August 2026'},items,traders:Object.values(traderRaw).map(t=>({...t,name:traderName(t.id)})),fleaMarket:ir.raw.fleaMarket,tasks,questItems,hideout,questMarkers,extracts,mapIntel,crafts,barters:barters.map(b=>({...b,traderName:traderName(b.trader)}))};
 const file=path.join(__dirname,'../data',`live-${mode}.json`);fs.writeFileSync(file+'.tmp',JSON.stringify(result));fs.renameSync(file+'.tmp',file);return result.meta;
}
if(require.main===module)sync(process.argv[2]).then(m=>console.log(m)).catch(e=>{console.error(e.message);process.exitCode=1;});
module.exports={sync};
