'use strict';
let craftFavoritesOnly=false;
(()=>{
 function filters(){
  const p=profile();p.mapPresets??={};const preset=p.mapPresets[p.map]??={};
  if(!preset.filters){preset.filters={hiddenContainers:[],lootItems:[],lootSearch:'',ownedDoorsOnly:false};
   // Move old profile-wide choices to the current map once; other maps start clean.
   for(const key of ['hiddenContainers','lootItems','lootSearch','ownedDoorsOnly'])if(p[key]!==undefined){preset.filters[key]=p[key];delete p[key];}
  }
  return preset.filters;
 }
 function persist(){const p=profile();p.mapPresets[p.map]={...p.mapPresets[p.map],layers:{...mapLayers},floor:mapFloor,zoom:mapZoom};save();}
 function mapFilters(){
  const p=profile(),f=filters(),g=data.mapIntel?.find(m=>m.mapKey===p.map&&m.name===(p.mapVariant||data.maps[p.map].locale.en))||data.mapIntel?.find(m=>m.mapKey===p.map),types=[...new Set((g?.lootContainers||[]).map(c=>c.name))].sort();
  const itemIds=[...new Set((g?.lootLoose||[]).flatMap(l=>l.items||[]))].filter(id=>data.itemIndex[id]).sort((a,b)=>data.itemIndex[a].name.localeCompare(data.itemIndex[b].name));
  return `<details id="advanced-map-filters" class="advanced-map-filters card" ${mapLayers.loot||mapLayers.containers?'open':''}><summary>Loot & container filters · ${escape(g?.name||data.maps[p.map].locale.en)}</summary><p class="subtext">${g?.lootContainers?.length||0} reference containers · ${g?.lootLoose?.length||0} loose-loot locations. Filters save automatically for this map.</p><div class="toolbar"><select id="loot-item-add" aria-label="Add loot item" ${itemIds.length?'':'disabled'}><option value="">${itemIds.length?'Add an item filter…':'No item records for this variant'}</option>${itemIds.map(id=>`<option value="${id}">${escape(data.itemIndex[id].name)}</option>`).join('')}</select><button data-advanced="clear-loot">Clear item filters</button><button data-advanced="reset-map-filters">Reset filters</button><label><input id="owned-doors-only" type="checkbox" ${f.ownedDoorsOnly?'checked':''}> Doors for my owned keys</label></div><div class="filter-chips">${(f.lootItems||[]).map(id=>`<button data-advanced="remove-loot" data-id="${id}">${escape(data.itemIndex[id]?.shortName||id)} ×</button>`).join('')}</div><div class="toolbar"><button data-advanced="show-containers">Show all container types</button><button data-advanced="hide-containers">Hide all container types</button></div><div class="container-types">${types.map(name=>`<label><input type="checkbox" data-container-type="${escape(name)}" ${!f.hiddenContainers?.includes(name)?'checked':''}> ${escape(name)} <small>(${g.lootContainers.filter(c=>c.name===name).length})</small></label>`).join('')||'<p class="subtext">No container coordinates supplied for this source variant. Try another variant.</p>'}</div><p id="loot-layer-status" class="subtext" role="status"></p><p class="subtext">Item chips match any selected item. Text search further narrows results. Enable Containers / Loose loot above to show markers. Locations are possible spawns, not guaranteed loot.</p></details>`;
 }
 function economy(){
  const p=profile(),b=p.bitcoinPlan||{},coin=data.items.find(i=>i.id==='59faff1d86f7746c51718c9c'),sale=b.sale??PlannerCore.traderOffers(coin||{})[0]?.priceRUB??0;
  const result=AdvancedCore.bitcoinEstimate({hours:Number(b.hours||24),sale:Number(sale),fuelHourly:Number(b.fuelHourly||0),investment:Number(b.investment||0)});
  return `<section class="card bitcoin-plan"><h2>Bitcoin investment planner</h2><p class="subtext">Enter the production interval shown in your game. Current trader quote is the initial sale estimate. Skills, GPUs, bonuses and fuel consumption vary; no fixed production formula is assumed.</p><div class="toolbar">${[['hours','Hours per coin',b.hours||24],['sale','Sale value ₽',sale],['fuelHourly','Fuel ₽ / hour',b.fuelHourly||0],['investment','Upgrade + GPUs ₽',b.investment||0]].map(([key,label,value])=>`<label>${label}<input data-bitcoin="${key}" type="number" min="${key==='hours'?'.1':'0'}" max="100000000" step="any" value="${value}"></label>`).join('')}</div><div class="price-grid"><div><span>COINS / DAY</span><b>${result?.perDay.toFixed(2)||'Unavailable'}</b></div><div><span>NET / DAY</span><b>${money(result?.daily)}</b></div><div><span>PAYBACK</span><b>${result?.payback===null?'No positive return':result?result.payback.toFixed(1)+' days':'Unavailable'}</b></div></div></section>`;
 }
 function weekly(){const weeks=AdvancedCore.weeklyRaids(profile().raids);return `<section class="card"><h2>Weekly raid history</h2><p class="subtext">From your recorded raids; UTC Monday week boundaries. No invented automatic records.</p>${weeks.slice(0,16).map(w=>`<div class="row"><div class="grow"><b>Week of ${w.week}</b><small>${escape(Object.entries(w.maps).map(([map,n])=>`${data.maps[map]?.locale.en||map}: ${n}`).join(' · '))}</small></div><span>${w.total} raids · ${Math.round(w.survived/w.total*100)}% survived</span></div>`).join('')||empty('Log a raid to start your history.')}</section>`;}
 function historyCard(id){const rows=(profile().marketHistory?.[id]||[]).filter(r=>r.mode===profile().mode);if(!rows.length)return'';const values=rows.map(r=>r.price),min=Math.min(...values),max=Math.max(...values),points=rows.map((r,i)=>`${20+(rows.length>1?i/(rows.length-1):.5)*460},${125-(r.price-min)/(max-min||1)*100}`).join(' ');return `<section class="card quote-history"><h3>Your price observations</h3><p class="subtext">${rows.length} community snapshots since ${new Date(rows[0].at).toLocaleDateString()}. Refresh while watching this item to build history.</p><svg viewBox="0 0 500 150" role="img" aria-label="Observed price history"><polyline points="${points}" fill="none" stroke="#b6cb87" stroke-width="3"/>${rows.map((r,i)=>`<circle cx="${20+(rows.length>1?i/(rows.length-1):.5)*460}" cy="${125-(r.price-min)/(max-min||1)*100}" r="4" fill="#ddc692"><title>${new Date(r.at).toLocaleString()}: ${money(r.price)}</title></circle>`).join('')}</svg><small>Range ${money(min)} – ${money(max)} · current ${money(values.at(-1))}</small></section>`;}
 function observe(){const p=profile(),at=Date.parse(data.meta.updatedUtc);if(!Number.isFinite(at))return;let changed=false;for(const id of p.watchlist){p.marketHistory??={};const old=p.marketHistory[id]||[],next=AdvancedCore.recordQuote(old,data.itemIndex[id],p.mode,at);if(next.length!==old.length||next.at(-1)?.at!==old.at(-1)?.at){p.marketHistory[id]=next;changed=true;}}if(changed)save();}
 function setup(){const s=state.settings;return `<details class="card setup-guide"><summary>Quick setup · screenshots, overlays and data</summary><ol><li>Set your game mode and player level in <a href="#settings">Preferences</a>.</li><li>Select your map. Choose a screenshot folder and enable filename watching if you want position updates.</li><li>Use F8 map, F9 prices, F10 quests when these bindings show Active. Drag a window header to move it and a corner to resize.</li><li>For item recognition, enable screen OCR, hover a visible item name and press F7. Confirm the detected variant.</li><li>For phone: Field tools → Phone & squad → Start sharing → scan the local QR code.</li></ol><p class="subtext">Screenshot watcher: ${s.autoPosition?'enabled':'off'} · Screen OCR: ${s.screenScan?'enabled':'off'} · Log watcher: ${s.logSync?'enabled — usable game events still unverified':'off'}. Use borderless for desktop overlays.</p></details>`;}
 function enhance(){
  if(overlay&&page!=='market')return;
  if(page==='overview')document.querySelector('.page-heading')?.insertAdjacentHTML('afterend',setup());
  if(page==='maps')document.querySelector('.map-extra-toolbar')?.insertAdjacentHTML('afterend',mapFilters());
  if(page==='hideout'){
   const layout=document.querySelector('.station-grid')?.closest('.card');if(layout)document.querySelector('.page-heading')?.insertAdjacentElement('afterend',layout);
   document.querySelectorAll('.station-tile').forEach((tile,i)=>{tile.dataset.advanced='station-focus';tile.dataset.id=data.hideout[i].id;tile.tabIndex=0;tile.setAttribute('role','button');tile.setAttribute('aria-label','Open '+data.hideout[i].name+' upgrade');});
   document.querySelector('#content')?.insertAdjacentHTML('beforeend',economy());
  }
  if(page==='crafts')document.querySelector('.craft-workbench .toolbar')?.insertAdjacentHTML('beforeend',`<label><input id="craft-favorites-only" type="checkbox" ${craftFavoritesOnly?'checked':''}> Favorites only</label>`);
  if(page==='field'&&fieldTab==='stats')document.querySelector('#content')?.insertAdjacentHTML('beforeend',weekly());
  if(page==='field'&&fieldTab==='squad'&&lanInfo?.qrCodes)document.querySelector('.pair-links')?.insertAdjacentHTML('beforeend',lanInfo.qrCodes.map(q=>`<figure class="pair-qr"><img src="${q.image}" alt="Private phone pairing QR"><figcaption>Scan on the same Wi-Fi. Pairing link is private.</figcaption></figure>`).join(''));
  if(page==='market'&&selectedItem){observe();document.querySelector('.price-card')?.insertAdjacentHTML('afterend',historyCard(selectedItem));}
  TCArt.decorate(document,page,profile());
 }
 document.addEventListener('click',e=>{const b=e.target.closest('[data-advanced]');if(!b)return;const p=profile(),f=filters();switch(b.dataset.advanced){case'clear-loot':f.lootItems=[];persist();render();break;case'remove-loot':f.lootItems=(f.lootItems||[]).filter(id=>id!==b.dataset.id);persist();render();break;case'reset-map-filters':f.hiddenContainers=[];f.lootItems=[];f.lootSearch='';f.ownedDoorsOnly=false;persist();render();break;case'show-containers':f.hiddenContainers=[];mapLayers.containers=true;persist();render();break;case'hide-containers':f.hiddenContainers=[...new Set((MapUI.group().lootContainers||[]).map(c=>c.name))];persist();render();break;case'station-focus':{const input=[...document.querySelectorAll('.hideout-level')].find(n=>n.dataset.id===b.dataset.id);input?.closest('.card')?.scrollIntoView({behavior:'smooth',block:'center'});input?.focus({preventScroll:true});break;}}});
 document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.station-tile')){e.preventDefault();e.target.click();}});
 document.addEventListener('change',e=>{const t=e.target,p=profile(),f=page==='maps'?filters():null;if(t.dataset.containerType){f.hiddenContainers??=[];f.hiddenContainers=t.checked?f.hiddenContainers.filter(n=>n!==t.dataset.containerType):[...new Set([...f.hiddenContainers,t.dataset.containerType])];persist();render();}if(t.id==='loot-item-add'&&t.value){f.lootItems=[...new Set([...(f.lootItems||[]),t.value])];mapLayers.loot=true;persist();render();}if(t.id==='owned-doors-only'){f.ownedDoorsOnly=t.checked;persist();render();}if(t.id==='craft-favorites-only'){craftFavoritesOnly=t.checked;render();}if(t.dataset.bitcoin){p.bitcoinPlan??={};p.bitcoinPlan[t.dataset.bitcoin]=Math.max(t.dataset.bitcoin==='hours'?.1:0,Math.min(100000000,Number(t.value)||0));save();render();}});
 function afterMount(){const status=document.getElementById('loot-layer-status');if(!status)return;const containers=document.querySelectorAll('.map-marker.container').length,loot=document.querySelectorAll('.map-marker.loot').length;status.textContent=`Containers: ${mapLayers.containers?containers+' shown':'layer off'} · Loose loot: ${mapLayers.loot?loot+' shown':'layer off'}`+((mapLayers.containers&&!containers||mapLayers.loot&&!loot)?' · No matching coordinates. Reset filters or check the selected source variant.':'');}
 window.AdvancedUI={enhance,observe,filters,persist,afterMount};
})();
