'use strict';
(()=>{
 const names=['overview','maps','quests','hideout','crafts','market','cultist','shopping','ammo','journal','settings','overlay','refresh','screenshot','export','save','add','remove','watch','close','search','zoom-in','zoom-out','fit'];
 const mapNames=['extract-pmc','extract-scav','extract-shared','transit','player','scav','boss','raider','quest','quest-item','pin','hazard','spawn-pmc','spawn-scav','cultist','vehicle'];
 const characters=['usec','bear','scav','raider','killa','tagilla','shturman','reshala','glukhar','sanitar','kaban','kollontay','knight','zryachiy','cultist','rogue'];
 const latest=['wedge','wedge-labs','basmach','gus','shadow-tagilla','vengeful-killa','glukhar-guard','cultist-warrior-v2'];
 const extra=['birdeye','big-pipe','partisan','black-div','af','cultist-warrior','guard','sniper-scav'];
 const lootIcons={container:'<path d="M5 10h22v17H5zM5 15h22M11 10V6h10v4M11 20h10M16 17v6"/>',loot:'<path d="m16 4 11 12-11 12L5 16zM10 16h12M16 10v12"/>',lock:'<path d="M8 14h16v13H8zM11 14V9a5 5 0 0 1 10 0v5M16 19v4"/>',switch:'<path d="M6 7h20v20H6zM11 17l10-9M11 17l6 6"/>'};
 function icon(name,kind='ui',className=''){if(kind==='map'&&lootIcons[name])return `<svg class="loot-symbol" viewBox="0 0 32 32" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2.3" stroke-linejoin="round">${lootIcons[name]}</svg>`;if(kind==='map'&&name==='spawn-shared')return '<span class="shared-spawn-art" aria-hidden="true">'+icon('spawn-pmc','map')+icon('spawn-scav','map')+'</span>';let list=names,columns=6,rows=4,file='ui-v1.png';if(kind==='map'){list=mapNames;columns=4;file='markers-v1.png';}if(kind==='character'){list=characters;columns=4;file='characters-v1.png';if(!list.includes(name)){list=extra;rows=2;file='characters-extra-v1.png';if(latest.includes(name)){list=latest;file='characters-latest-v1.png';}}}let index=list.indexOf(name);if(index<0)index=kind==='map'?6:kind==='character'?3:0;const col=index%columns,row=Math.floor(index/columns);return`<span class="art-sprite ${kind==='character'?'portrait-sprite':''} ${className}" aria-hidden="true" style="background-image:url('/art/${file}');background-size:${columns*100}% ${rows*100}%;background-position:${col/(columns-1)*100}% ${row/(rows-1)*100}%"></span>`;}
 const actions={pin:'watch',watch:'watch','item-detail':'search','close-item':'close',sync:'refresh','zoom-in':'zoom-in','zoom-out':'zoom-out','zoom-reset':'fit','position-apply':'maps',screenshot:'screenshot','clear-pins':'remove',scan:'screenshot',capture:'screenshot','cultist-add':'cultist','clear-slot':'remove','circle-start':'cultist','circle-stop':'close','raid-save':'journal','profile-save':'save','profile-new':'add','backup-export':'export','backup-import':'screenshot','export-list':'export','screenshot-folder':'maps','overlay-hide':'close'};
 function decorate(scope,page,profile){for(const button of scope.querySelectorAll('button:not(.map-marker):not(.art-button):not([data-no-art])')){const key=button.dataset.action,route=button.dataset.route,feature=button.dataset.feature,tool=button.dataset.tool,kind=feature?({tab:'maps','tree-select':'quests',item:'market','quest-map':'maps','quest-active':'quests','quest-complete':'save','quest-hide':'close','counter-plus':'add','counter-minus':'remove','craft-start':'crafts','craft-collect':'save','craft-cancel':'close','craft-favorite':'watch','items-overlay':'market','tasks-overlay':'quests','logs-import':'refresh','logs-folder':'settings','scan-cursor':'screenshot','stats-export':'export','lan-start':'overlay','lan-stop':'close','squad-join':'add','squad-leave':'close','fkey-preset':'settings','menu-minimap':'maps','menu-tree':'quests','menu-close':'close','price-close':'close','special-start':'crafts','story-add':'add','story-delete':'remove','gear-shopping':'shopping','gear-clear':'close','map-preset-save':'save','map-panel':'quests'}[feature]||'settings'):tool?({lock:'overlay',follow:'maps',center:'maps','reset-overlay':'fit','save-hotkeys':'save','reset-hotkeys':'refresh','close-help':'close'}[tool]||'settings'):button.dataset.mapAction==='reset-raid'?'refresh':button.dataset.mapAction==='clear-selection'?'close':button.dataset.mapAction?'maps':button.id==='overlay-button'?'overlay':button.id==='settings-shortcut'?'settings':actions[key]||route||'save';if(!button.querySelector('.art-sprite'))button.insertAdjacentHTML('afterbegin',icon(kind));button.classList.add('art-button');}
 for(const i of scope.querySelectorAll('.task-icon:not(.has-art)')){i.innerHTML=icon(i.closest('.item-row')?'shopping':'quests');i.classList.add('has-art');}
 for(const [index,card]of [...scope.querySelectorAll('.stats>.card')].entries()){if(!card.querySelector('.stat-art'))card.insertAdjacentHTML('afterbegin',icon(['quests','hideout',profile.faction==='BEAR'?'bear':'usec','watch'][index],index===2?'character':'ui','stat-art'));}
 const head=scope.querySelector('.page-heading');if(head&&!head.classList.contains('field-heading')){head.classList.add('field-heading');head.insertAdjacentHTML('afterbegin',icon(page,'ui','heading-art'));}
 const mark=scope.querySelector('.brandmark');if(mark&&!mark.classList.contains('brand-art')){mark.classList.add('brand-art');mark.innerHTML=icon('pin','map');}
 const select=scope.querySelector('#profile-select');if(select){scope.querySelector('.operator-emblem')?.remove();select.insertAdjacentHTML('beforebegin',icon(profile.faction==='BEAR'?'bear':'usec','character','operator-emblem'));}
 }
 window.TCArt={icon,decorate};
})();
