const {app,BrowserWindow,ipcMain,dialog,globalShortcut,desktopCapturer,screen,shell}=require('electron');
const fs=require('node:fs'),path=require('node:path');
const {createServer}=require('./server.cjs'),{parseScreenshot,parseScreenshotPose,matchItems}=require('./core.cjs');
app.setName('Tarkov Companion');app.setPath('userData',process.env.TC_TEST_USER_DATA||path.join(app.getPath('appData'),'TarkovCompanion'));
let overlayController,logSync,sharing;let main,server,origin,store={},scanning=false,watcher,watchedFolder,timer;
const statePath=()=>path.join(app.getPath('userData'),'state.json');
const prefs=()=>({preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true});
const ownsLock=app.requestSingleInstanceLock();if(!ownsLock)app.quit();app.on('second-instance',()=>{if(main){if(main.isMinimized())main.restore();main.show();main.focus();}});
function configureWatcher(){const folder=store.settings?.autoPosition?store.settings.screenshotFolder:null;if(folder===watchedFolder)return;watcher?.close();watcher=null;watchedFolder=folder;if(!folder)return;try{watcher=fs.watch(folder,(_event,name)=>{if(!name||!parseScreenshot(name))return;clearTimeout(timer);timer=setTimeout(()=>{if(main&&!main.isDestroyed())main.webContents.send('position:update',{name:String(name),position:parseScreenshotPose(name)});},350);});watcher.on('error',e=>{watchedFolder=null;main?.webContents.send('position:update',{error:'Screenshot folder watcher stopped: '+e.message});});}catch(e){watchedFolder=null;main?.webContents.send('position:update',{error:'Unable to watch screenshot folder: '+e.message});}}
function secureWindow(win){win.webContents.setWindowOpenHandler(({url})=>{if(/^https:\/\/(?:tarkov\.dev|cultistcircle\.com|escapefromtarkov\.fandom\.com|www\.escapefromtarkov\.com|t\.me)\//.test(url))shell.openExternal(url);return{action:'deny'};});win.webContents.on('will-navigate',(e,url)=>{if(!url.startsWith(origin+'/'))e.preventDefault();});}
async function importPosition(latest=false){let file;if(latest){const folder=store.settings?.screenshotFolder;if(!folder)return{error:'Choose your EFT screenshot folder in Preferences first.'};const files=fs.readdirSync(folder).filter(f=>parseScreenshot(f)).map(name=>({name,at:fs.statSync(path.join(folder,name)).mtimeMs})).sort((a,b)=>b.at-a.at);if(!files.length)return{error:'No screenshots with coordinates in the selected folder.'};file=path.join(folder,files[0].name);}else{const result=await dialog.showOpenDialog(main,{title:'Import an EFT screenshot position',properties:['openFile'],filters:[{name:'Screenshots',extensions:['png','jpg','jpeg']}]});if(result.canceled)return{cancelled:true};file=result.filePaths[0];}return{name:path.basename(file),position:parseScreenshotPose(file)};}
async function scan(options){const capture=options===true||options?.capture===true;const cursorCrop=options?.cursor===true;if(scanning)throw Error('A scan is already running');if(capture&&!store.settings?.screenScan)throw Error('Screen capture is disabled');scanning=true;let worker;try{let image;if(capture){const display=screen.getDisplayNearestPoint(screen.getCursorScreenPoint());const size={width:Math.round(display.size.width*display.scaleFactor),height:Math.round(display.size.height*display.scaleFactor)};const captureOverlays=overlayController?.windows()||[];const visibleOverlays=captureOverlays.filter(w=>w.isVisible());const wasMain=main.isVisible();main.hide();for(const w of captureOverlays)w.hide();try{await new Promise(r=>setTimeout(r,250));const sources=await desktopCapturer.getSources({types:['screen'],thumbnailSize:size});const source=sources.find(s=>s.display_id===String(display.id))||sources[0];if(!source)throw Error('No display available');let captured=source.thumbnail;if(cursorCrop){const cursor=screen.getCursorScreenPoint(),scale=display.scaleFactor,px=(cursor.x-display.bounds.x)*scale,py=(cursor.y-display.bounds.y)*scale,dim=captured.getSize();const width=Math.min(dim.width,Math.round(900*scale)),height=Math.min(dim.height,Math.round(420*scale));captured=captured.crop({x:Math.max(0,Math.min(dim.width-width,Math.round(px-width/2))),y:Math.max(0,Math.min(dim.height-height,Math.round(py-height/2))),width,height});}image=captured.toPNG();}finally{if(wasMain)main.showInactive();for(const w of visibleOverlays)if(!w.isDestroyed())w.showInactive();}}else{const picked=await dialog.showOpenDialog(main,{title:'Choose a cropped screenshot with the item name visible',properties:['openFile'],filters:[{name:'Images',extensions:['png','jpg','jpeg']}]});if(picked.canceled)return{cancelled:true};const file=picked.filePaths[0];if(fs.statSync(file).size>20000000)throw Error('Choose an image smaller than 20 MB');image=fs.readFileSync(file);}
 const {createWorker}=require('tesseract.js');worker=await createWorker('eng',1,{cachePath:app.getPath('userData')});const {data}=await worker.recognize(image);const p=store.profiles?.find(p=>p.id===store.active),mode=p?.mode||'regular';const file=path.join(__dirname,'data',`live-${mode}.json`);const items=JSON.parse(fs.readFileSync(fs.existsSync(file)?file:path.join(__dirname,'data/reference.json'),'utf8')).items;return{text:data.text,matches:matchItems(data.text,items)};
 }finally{await worker?.terminate();scanning=false;}}
function trusted(event){if(![main?.webContents.id,...(overlayController?.windows()||[]).map(w=>w.webContents.id)].includes(event.sender.id))throw Error('Untrusted caller');}
if(ownsLock)app.whenReady().then(async()=>{fs.mkdirSync(app.getPath('userData'),{recursive:true});try{store=JSON.parse(fs.readFileSync(statePath(),'utf8'));}catch{}server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`;
 main=new BrowserWindow({width:1440,height:940,minWidth:900,minHeight:650,backgroundColor:'#101312',webPreferences:prefs(),title:'Tarkov Companion',autoHideMenuBar:true});secureWindow(main);
 ipcMain.handle('state:load',e=>{trusted(e);return store;});ipcMain.handle('state:save',(e,value)=>{trusted(e);if(value?.version!==1||!Array.isArray(value.profiles)||JSON.stringify(value).length>5000000)throw Error('Invalid state');store=value;fs.writeFileSync(statePath()+'.tmp',JSON.stringify(value));fs.renameSync(statePath()+'.tmp',statePath());configureWatcher();logSync?.configure();return true;});
 ipcMain.handle('position:import',e=>{trusted(e);return importPosition();});ipcMain.handle('folder:choose',async e=>{trusted(e);const r=await dialog.showOpenDialog(main,{properties:['openDirectory'],title:'Select only your EFT screenshots folder'});return r.canceled?null:r.filePaths[0];});ipcMain.handle('scan:run',(e,capture)=>{trusted(e);return scan(capture);});overlayController=require('./overlay-manager.cjs')({app,ipcMain,trusted,prefs,secureWindow,origin,getMain:()=>main,position:async()=>{try{main.webContents.send('position:update',await importPosition(true));}catch(e){main.webContents.send('position:update',{error:e.message});}},scan:()=>main.webContents.send('scan:request',{cursor:true})});

 sharing=require('./sharing.cjs')({onMembers:members=>{if(main&&!main.isDestroyed())main.webContents.send('squad:update',members);overlayController?.publish('squad:update',members);}});
 ipcMain.handle('sharing:start',(e,value)=>{trusted(e);return sharing.start(value).then(async info=>({...info,qrCodes:await Promise.all(info.urls.map(async url=>({url,image:await require('qrcode').toDataURL(url,{width:200,margin:2})})))}));});ipcMain.handle('sharing:stop',e=>{trusted(e);sharing.stop();});ipcMain.handle('sharing:update',(e,value)=>{trusted(e);return sharing.update(value);});ipcMain.handle('sharing:join',(e,url,value)=>{trusted(e);return sharing.join(url,value);});
 ipcMain.handle('scan:latest',e=>{trusted(e);return overlayController.latestScan();});
 ipcMain.handle('scan:publish',(e,value)=>{trusted(e);if(!value||!Array.isArray(value.ids)||value.ids.length>10)throw Error('Invalid scan candidates');overlayController.publish('scan:result',value);});
 ipcMain.handle('logs:choose',async e=>{trusted(e);const r=await dialog.showOpenDialog(main,{title:'Choose EFT client Logs folder',defaultPath:'C:/Battlestate Games/Logs',properties:['openDirectory']});return r.canceled?null:r.filePaths[0];});
 ipcMain.handle('logs:import',e=>{trusted(e);if(!store.settings?.logsFolder)throw Error('Choose your client Logs folder first.');return logSync.importNow();});
 logSync=require('./log-sync.cjs').createLogSync({getSettings:()=>store.settings||{},userData:app.getPath('userData'),onEvents:events=>main.webContents.send('logs:events',events)});logSync.configure();
 main.on('closed',()=>{overlayController?.destroy();logSync?.close();sharing?.stop();app.quit();});await main.loadURL(origin+'/');
});
app.on('will-quit',()=>{globalShortcut.unregisterAll();watcher?.close();clearTimeout(timer);server?.close();});
