/* Reference geometry and manually confirmed exit status; no live game access. */
function pointSegmentDistance(p,a,b){const dx=b.x-a.x,dz=b.z-a.z,length=dx*dx+dz*dz;const t=length?Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.z-a.z)*dz)/length)):0;return Math.hypot(p.x-a.x-t*dx,p.z-a.z-t*dz);}
function horizontalDistance(p,exit){const polygon=exit.outline;if(!polygon||polygon.length<3)return Math.hypot(p.x-exit.position.x,p.z-exit.position.z);let inside=false,best=Infinity;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j];if((a.z>p.z)!==(b.z>p.z)&&p.x<(b.x-a.x)*(p.z-a.z)/(b.z-a.z)+a.x)inside=!inside;best=Math.min(best,pointSegmentDistance(p,a,b));}return inside?0:best;}
function proximity(p,exit,radius=25){if(!p||!Number.isFinite(p.x)||!Number.isFinite(p.z)||!exit.position)return{nearby:false,distance:null,levelKnown:false,sameLevel:false};const distance=horizontalDistance(p,exit),levelKnown=Number.isFinite(p.y);let sameLevel=true;if(levelKnown){if(Number.isFinite(exit.bottom)&&Number.isFinite(exit.top))sameLevel=p.y>=exit.bottom-2&&p.y<=exit.top+2;else if(Number.isFinite(exit.position.y))sameLevel=Math.abs(p.y-exit.position.y)<=8;}return{distance,nearby:distance<=radius&&sameLevel,levelKnown,sameLevel};}
function mapToWorld(location,config,worldToMap){const zero=worldToMap({x:0,z:0},config),x=worldToMap({x:1,z:0},config),z=worldToMap({x:0,z:1},config);const a=x.nx-zero.nx,b=z.nx-zero.nx,c=x.ny-zero.ny,d=z.ny-zero.ny,det=a*d-b*c;if(Math.abs(det)<1e-14)return null;const u=location.nx-zero.nx,v=location.ny-zero.ny;return{x:(u*d-b*v)/det,z:(a*v-u*c)/det};}
function exitKey(mode,map,kind,exit){return[mode,map,kind,exit.id||'',exit.name||exit.destination||'',exit.faction||'',exit.position?.x,exit.position?.z].join(':');}
function exitState(exit,{player=null,role='pmc',manual='unknown',radius=25}={}){const near=proximity(player,exit,radius),faction=exit.faction||'shared',eligible=faction==='shared'||faction==='all'||faction===role;const blocked=!eligible||manual==='unavailable';return{...near,eligible,manual,highlight:near.nearby&&!blocked,available:manual==='available'&&eligible,blocked};}
function spriteName(name){const s=String(name).toLowerCase().replace(/[^a-z]/g,'');const aliases={cultistpriest:'cultist',cultistwarrior:'cultist-warrior-v2',blackdiv:'black-div',blackdivision:'black-div',af:'af',bigpipe:'big-pipe',birdeye:'birdeye',shadowoftagilla:'shadow-tagilla',vengefulkilla:'vengeful-killa',gluhar:'glukhar',thewedge:'wedge',thewedgelabs:'wedge-labs',basmach:'basmach',gus:'gus'};if(aliases[s])return aliases[s];if(s.includes('sniper'))return'sniper-scav';if(s.includes('glukhar')&&s.includes('guard'))return'glukhar-guard';if(s.includes('guard'))return'guard';for(const boss of ['killa','tagilla','shturman','reshala','glukhar','sanitar','kaban','kollontay','knight','zryachiy','partisan','rogue','raider'])if(s.includes(boss))return boss;return null;}
function spawnKind(sides=[]){const all=sides.includes('all'),pmc=sides.some(s=>['pmc','usec','bear'].includes(s)),scav=sides.includes('scav');return all||pmc&&scav?'shared':pmc?'pmc':scav?'scav':'unknown';}
const api={horizontalDistance,proximity,mapToWorld,exitKey,exitState,spawnKind,spriteName};
if(typeof module!=='undefined')module.exports=api;else window.MapLogic=api;
