const {BrowserWindow,screen,globalShortcut}=require('electron');
const fs=require('node:fs'),path=require('node:path'),keys=require('./keybinds.cjs');
const legacy={overlay:'CommandOrControl+Shift+O',position:'CommandOrControl+Shift+M',scan:'CommandOrControl+Shift+F',lock:'CommandOrControl+Shift+X',focus:'CommandOrControl+Shift+T',center:'CommandOrControl+Shift+C',zoomIn:'CommandOrControl+Shift+Up',zoomOut:'CommandOrControl+Shift+Down',items:'',tasks:''};
module.exports=function({app,ipcMain,trusted,prefs,secureWindow,origin,getMain,position,scan}){
 const file=path.join(app.getPath('userData'),'desktop-preferences.json');let saved={};try{saved=JSON.parse(fs.readFileSync(file,'utf8'));}catch{}
 const records=new Map();let latestScan=null;let status={},lastKind='maps',control=keys.inspect();
 const write=()=>{fs.writeFileSync(file+'.tmp',JSON.stringify(saved));fs.renameSync(file+'.tmp',file);};
 function snapshot(kind='maps'){const r=records.get(kind);return{kind,locked:r?.locked||false,visible:Boolean(r?.win.isVisible()),bounds:r?.win.getBounds()||saved.windows?.[kind]||saved.bounds,shortcuts:{...legacy,...saved.shortcuts},status,gameControls:control,overlays:[...records].map(([kind,r])=>({kind,visible:r.win.isVisible(),locked:r.locked}))};}
 function broadcast(){const m=getMain();if(m&&!m.isDestroyed())m.webContents.send('overlay:status',snapshot());for(const [kind,r]of records)if(!r.win.isDestroyed())r.win.webContents.send('overlay:status',snapshot(kind));}
 function clamp(b){const a=screen.getDisplayMatching(b).workArea,width=Math.min(a.width,Math.max(300,b.width||420)),height=Math.min(a.height,Math.max(300,b.height||460));return{width,height,x:Math.round(Math.max(a.x,Math.min(a.x+a.width-width,b.x))),y:Math.round(Math.max(a.y,Math.min(a.y+a.height-height,b.y)))};}
 function flush(kind){const r=records.get(kind);if(!r)return;clearTimeout(r.timer);if(!r.win.isDestroyed()){saved.windows??={};saved.windows[kind]=r.win.getBounds();if(kind==='maps')saved.bounds=saved.windows[kind];write();}}
 function toggle(show,kind='maps'){if(!['maps','items','tasks'].includes(kind))throw Error('Unknown overlay');lastKind=kind;let r=records.get(kind);if(show===false&&!r)return;
  if(!r){const a=screen.getPrimaryDisplay().workArea,b=clamp(saved.windows?.[kind]||(kind==='maps'?saved.bounds:null)||{x:a.x+a.width-(kind==='items'?840:450),y:a.y+60,width:kind==='items'?440:420,height:kind==='items'?600:460});
   const win=new BrowserWindow({...b,minWidth:300,minHeight:300,frame:false,show:false,resizable:true,alwaysOnTop:true,skipTaskbar:true,backgroundColor:'#101810',webPreferences:prefs(),title:'Tarkov Companion '+kind});r={win,locked:false,timer:null};records.set(kind,r);secureWindow(win);win.setAlwaysOnTop(true,'screen-saver');win.setVisibleOnAllWorkspaces(true,{visibleOnFullScreen:true});win.setOpacity((saved.opacity||95)/100);win.loadURL(origin+`/?overlay=1&panel=${kind}#${kind==='items'?'market':kind==='tasks'?'quests':'maps'}`);win.once('ready-to-show',()=>{win.showInactive();broadcast();});win.webContents.on('did-finish-load',()=>{if(kind==='items'&&latestScan)setTimeout(()=>{if(!win.isDestroyed())win.webContents.send('scan:result',latestScan);},300);});win.on('focus',()=>lastKind=kind);
   const remember=()=>{clearTimeout(r.timer);r.timer=setTimeout(()=>flush(kind),180);};win.on('move',remember);win.on('resize',remember);win.on('close',()=>flush(kind));win.on('show',broadcast);win.on('hide',broadcast);win.on('closed',()=>{clearTimeout(r.timer);records.delete(kind);broadcast();});return;
  }if(show===false||(r.win.isVisible()&&show!==true))r.win.hide();else{r.win.setAlwaysOnTop(true,'screen-saver');r.win.showInactive();}broadcast();
 }
 function senderKind(e){return[...records].find(([,r])=>r.win.webContents.id===e.sender.id)?.[0]||'maps';}
 function lock(kind=lastKind){const r=records.get(kind);if(!r)return;r.locked=!r.locked;r.win.setIgnoreMouseEvents(r.locked,{forward:true});broadcast();}
 const send=action=>records.get('maps')?.win.webContents.send('overlay:command',action);
 const actions={overlay:()=>toggle(undefined,'maps'),items:()=>toggle(undefined,'items'),tasks:()=>toggle(undefined,'tasks'),position,scan,lock,focus:()=>{const m=getMain();if(m.isMinimized())m.restore();m.show();m.focus();},center:()=>send('center'),zoomIn:()=>send('zoom-in'),zoomOut:()=>send('zoom-out')};
 function register(values){globalShortcut.unregisterAll();saved.shortcuts={...legacy,...values};status={};const used=new Set();control=keys.inspect();for(const [id,key]of Object.entries(saved.shortcuts)){if(!actions[id])continue;if(!key){status[id]='Disabled';continue;}const clash=keys.conflict(key,control);if(clash){status[id]='Tarkov conflict: '+clash;continue;}if(used.has(key.toLowerCase())){status[id]='Duplicate';continue;}used.add(key.toLowerCase());try{status[id]=globalShortcut.register(key,actions[id])?'Active':'Unavailable / in use';}catch{status[id]='Invalid shortcut';}}write();broadcast();return snapshot();}
 function preset(){const next={...legacy,...saved.shortcuts},assign={overlay:'F8',items:'F9',tasks:'F10',position:'F6',scan:'F7',lock:'F11'};control=keys.inspect();if(!control.verified)throw Error('Tarkov controls could not be verified; existing bindings preserved.');for(const [id,key]of Object.entries(assign))if(control.freeFunctionKeys.includes(key)&&(next[id]===legacy[id]||!next[id]))next[id]=key;saved.fKeyVersion=1;return register(next);}
 ipcMain.handle('overlay:status',e=>{trusted(e);return snapshot(senderKind(e));});ipcMain.handle('shortcuts:save',(e,values)=>{trusted(e);if(!values||typeof values!=='object'||Object.keys(values).some(k=>!(k in legacy)||typeof values[k]!=='string'||values[k].length>80))throw Error('Invalid shortcuts');return register(values);});ipcMain.handle('shortcuts:preset',e=>{trusted(e);return preset();});
 ipcMain.handle('overlay:toggle',(e,show)=>{trusted(e);toggle(show,senderKind(e));});ipcMain.handle('overlay:open',(e,kind,show)=>{trusted(e);toggle(show===true?true:undefined,kind);});ipcMain.handle('overlay:lock',e=>{trusted(e);const kind=senderKind(e);lock(kind);return snapshot(kind);});
 ipcMain.handle('overlay:opacity',(e,value)=>{trusted(e);if(Number.isFinite(value)){saved.opacity=Math.round(Math.max(.4,Math.min(1,value))*100);for(const r of records.values())r.win.setOpacity(saved.opacity/100);write();}});
 ipcMain.handle('overlay:resize',(e,b)=>{trusted(e);const r=records.get(senderKind(e));if(!r||e.sender.id!==r.win.webContents.id||r.locked)return;if(b&&['width','height'].every(k=>Number.isFinite(b[k])))r.win.setBounds(clamp({...r.win.getBounds(),width:Math.round(b.width),height:Math.round(b.height)}));});
 ipcMain.handle('overlay:reset',e=>{trusted(e);const kind=senderKind(e),a=screen.getPrimaryDisplay().workArea,b={x:a.x+a.width-450,y:a.y+60,width:420,height:460};saved.windows??={};saved.windows[kind]=b;if(kind==='maps')saved.bounds=b;records.get(kind)?.win.setBounds(clamp(b));write();broadcast();});
 if(!saved.fKeyVersion&&control.verified)preset();else register(saved.shortcuts);
 return{toggle,latestScan:()=>latestScan,window:()=>records.get('maps')?.win,windows:()=>[...records.values()].map(r=>r.win),publish:(channel,value)=>{if(channel==='scan:result')latestScan=value;for(const r of records.values())r.win.webContents.send(channel,value);},destroy:()=>{for(const kind of records.keys()){flush(kind);records.get(kind)?.win.destroy();}}};
};
