(function(root){
 const id=v=>typeof v==='string'?v:v?.id||v?.item;
 function price(item,overrides={}){const n=overrides[item?.id];return Number.isFinite(n)&&n>=0?n:(item?.lastLowPrice??item?.avg24hPrice??null);}
 function traderOffers(item){return(item?.sellFor||[]).filter(s=>Number.isFinite(s.priceRUB)&&s.priceRUB>=0&&!/flea/i.test(s.vendor?.name||s.source||'')).sort((a,b)=>b.priceRUB-a.priceRUB);}
 function prerequisites(task,tasks){const index=Object.fromEntries(tasks.map(t=>[t.id,t])),result=[],seen=new Set([task.id]);function visit(t,depth){for(const r of t.requirements||[]){const q=index[id(r.task)||r.id];if(!q||seen.has(q.id))continue;seen.add(q.id);visit(q,depth+1);result.push({task:q,depth});}}visit(task,1);return result;}
 function recommendations(tasks,status,map){return tasks.filter(t=>['available','active'].includes(status(t))).map(t=>{const next=tasks.filter(q=>(q.requirements||[]).some(r=>(r.id||id(r.task))===t.id)).length;const score=next*3+(t.kappaRequired?4:0)+(t.lightkeeperRequired?5:0)+(status(t)==='active'?6:0)+(t.map===map?3:0);return{task:t,score,reasons:[next?`${next} follow-up unlocks`:null,t.kappaRequired?'Kappa progress':null,t.lightkeeperRequired?'Lightkeeper progress':null,status(t)==='active'?'Already active':null,t.map===map?'Your selected map':null].filter(Boolean)};}).sort((a,b)=>b.score-a.score||a.task.name.localeCompare(b.task.name));}
 function craftEstimate(c,items,overrides={},feePercent=5,fuelHourly=0){const inputs=(c.requiredItems||[]).filter(r=>!r.attributes?.tool),known=inputs.every(r=>price(items[r.item],overrides)!==null),cost=known?inputs.reduce((n,r)=>n+price(items[r.item],overrides)*r.count,0):null,revenue=price(items[c.productItem.item],overrides),gross=revenue===null?null:revenue*c.productItem.count,fee=gross===null?null:gross*Math.max(0,Math.min(100,feePercent))/100,fuel=Math.max(0,fuelHourly)*c.duration/3600;return{cost,gross,fee,fuel,net:cost===null||gross===null?null:gross-cost-fee-fuel};}
 function itemUses(itemId,data,status){return{quests:data.tasks.filter(t=>status(t)!=='done'&&(t.objectives||[]).some(o=>o.itemId===itemId||(o.items||[]).includes(itemId))),crafts:(data.crafts||[]).filter(c=>(c.requiredItems||[]).some(r=>r.item===itemId)||c.productItem.item===itemId),barters:(data.barters||[]).filter(b=>(b.requiredItems||[]).some(r=>r.item===itemId)||b.offeredItem.item===itemId)};}
 function gearWarnings(gear,items){const chosen=Object.values(gear||{}).filter(Boolean),warnings=[];for(const a of chosen){const item=items[a];if(!item)continue;for(const b of chosen)if(a!==b&&(item.conflictingItems||[]).includes(b))warnings.push(`${item.shortName||item.name} conflicts with ${items[b]?.shortName||b}`);}const weapon=items[gear?.weapon],ammo=items[gear?.ammo];if(weapon&&ammo&&weapon.properties?.allowedAmmo&&!weapon.properties.allowedAmmo.includes(ammo.id))warnings.push('Ammo is not listed as compatible with this weapon.');return [...new Set(warnings)];}
 function parseLogLine(line){const events=[];const stamp=/^(\d{4}-\d\d-\d\d[^|]+)\|/.exec(line)?.[1];let body;const at=line.indexOf('{');if(at>=0){try{body=JSON.parse(line.slice(at));}catch{}}
 const statuses={started:'active',accepted:'active',success:'done',completed:'done',complete:'done',fail:'failed',failed:'failed',failrestartable:'failed',notstarted:'auto',locked:'auto',availableforstart:'auto',availableforfinish:'active',1:'auto',2:'active',3:'active',4:'done',5:'failed',6:'failed'};
 const visit=(v,mode=null)=>{if(!v||typeof v!=='object')return;mode=v.gameMode||v.mode||mode;const key=v.questId||v.qid||(v.status!==undefined&&v._id);const raw=String(v.status??v.questStatus??'').toLowerCase();if(typeof key==='string'&&/^[a-f0-9]{24}$/.test(key)&&statuses[raw])events.push({type:'quest',id:key,status:statuses[raw],mode,at:stamp});if(v.type==='RaidStarted'&&typeof v.map==='string')events.push({type:'raid',map:v.map,mode,at:stamp});for(const value of Object.values(v))if(value&&typeof value==='object')if(Array.isArray(value))value.forEach(n=>visit(n,mode));else visit(value,mode);};visit(body);
 const match=!body&&/Quest(?:StatusChanged| status changed)[^\r\n]*?([a-f0-9]{24})[^\r\n]*?(Started|Success|Completed|FailRestartable|Failed|AvailableForFinish|NotStarted)/i.exec(line);if(match)events.push({type:'quest',id:match[1],status:statuses[match[2].toLowerCase()],mode:null,at:stamp});return events;}
 const api={price,traderOffers,prerequisites,recommendations,craftEstimate,itemUses,gearWarnings,parseLogLine};if(typeof module!=='undefined')module.exports=api;else root.PlannerCore=api;
})(typeof window==='undefined'?globalThis:window);
