'use strict';
(()=>{
 function rows(){const p=profile();return QuestCore.plan(data.tasks,p,taskStatus,data.maps[p.map]?.locale.en);}
 function tracked(){const p=profile();return [...new Set([...p.pinned,...(p.autoTaskTrack!==false?rows().filter(r=>!r.ready&&(r.locations.includes(data.maps[p.map]?.locale.en)||!r.locations.length)).slice(0,6).map(r=>r.task.id):[])])];}
 function board(){const p=profile(),plan=rows(),groups=new Map();for(const r of plan){const names=r.ready?['Ready to hand in']:r.locations.length?r.locations:['Any map / trader'];for(const name of names){const list=groups.get(name)||[];list.push(r);groups.set(name,list);}}const sync=p.lastQuestSync;if(overlay)return `<section class="card quest-operations"><b>Raid task board</b><p class="subtext">${plan.length} active · ${plan.filter(r=>r.ready).length} ready to hand in · quiet log updates</p><label><input id="auto-task-track" type="checkbox" ${p.autoTaskTrack!==false?'checked':''}> Auto-track selected map</label></section>`;return `<section class="card quest-operations"><div class="section-head"><h2>Raid task board</h2><label><input id="auto-task-track" type="checkbox" ${p.autoTaskTrack!==false?'checked':''}> Auto-track raid tasks</label></div><p class="subtext">Groups your active tasks by map and prioritizes hand-ins, pinned goals and follow-up unlocks. Automatically tracks up to six tasks for your selected map; your manual pins stay yours.</p><p class="quest-sync-line">${state.settings.logSync?'Watching client logs quietly':'Quest log sync paused'} · ${sync?'Last recognized quest change '+new Date(sync).toLocaleString():'No recognized quest progress yet'} <button data-quest-ui="sync">Sync quests</button></p>${plan.length?`<div class="quest-plan-grid">${[...groups].sort(([a],[b])=>a==='Ready to hand in'?-1:b==='Ready to hand in'?1:a===data.maps[p.map]?.locale.en?-1:b===data.maps[p.map]?.locale.en?1:a.localeCompare(b)).map(([name,list])=>`<div class="quest-plan-group"><h3>${escape(name)} <span class="badge">${list.length}</span></h3>${list.slice(0,8).map(r=>`<button data-quest-ui="find" data-id="${r.task.id}"><b>${escape(r.task.name)}</b><small>${escape(r.task.trader)} · ${r.ready?'Hand-in state recorded':r.remaining.length+' objective'+(r.remaining.length===1?'':'s')+' remaining'}${r.unlocks?' · '+r.unlocks+' follow-up unlocks':''}</small></button>`).join('')}</div>`).join('')}</div>`:empty('Accept tasks in game, then Sync. If the client has no readable quest records, set your active tasks once here; the board organizes them automatically.')}<p class="subtext">Community data supplies requirements, not your personal completion. A hand-in or checklist is never assumed to mean the quest has been completed in game.</p></section>`;}
 function enhance(){if(page!=='quests')return;const toolbar=document.querySelector('#content>.toolbar');if(toolbar&&!document.querySelector('.quest-operations'))toolbar.insertAdjacentHTML('afterend',board());for(const card of document.querySelectorAll('.task-card')){const id=card.querySelector('.task-status')?.dataset.id,source=profile().questSources?.[id];if(source)card.querySelector('.task-meta')?.insertAdjacentHTML('beforeend',`<span class="badge">${source.status==='ready'?'READY TO HAND IN':'LOG SYNCED'}</span>`);}TCArt.decorate(document,page,profile());}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-quest-ui]');if(!b)return;if(b.dataset.questUi==='sync')SyncUI.run();else{search=data.tasks.find(t=>t.id===b.dataset.id)?.name||'';questFilter='all';render();}});
 document.addEventListener('change',e=>{if(e.target.id==='auto-task-track'){profile().autoTaskTrack=e.target.checked;save();render();}});
 window.QuestUI={enhance,tracked,rows};
})();
