const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
module.exports=function({onMembers}){let server,token,payload={},members=new Map(),port;
 const clean=v=>{if(!v||typeof v.name!=='string'||!['regular','pve','pvp-season'].includes(v.mode))throw Error('Invalid squad update');const loc=v.location;return{name:v.name.slice(0,60),mode:v.mode,map:String(v.map||'customs').slice(0,40),location:loc&&Number.isFinite(loc.nx)&&Number.isFinite(loc.ny)?{nx:Math.max(0,Math.min(1,loc.nx)),ny:Math.max(0,Math.min(1,loc.ny)),y:Number.isFinite(loc.y)?loc.y:null,at:loc.at}:null,needs:Array.isArray(v.needs)?v.needs.slice(0,500).map(r=>({id:String(r.id).slice(0,40),name:String(r.name).slice(0,150),count:Math.max(0,Number(r.count)||0)})):[],questMaps:Object.fromEntries(Object.entries(v.questMaps||{}).slice(0,20).map(([k,n])=>[k.slice(0,40),Math.max(0,Math.min(1000,Number(n)||0))])),at:Date.now()};};
 function current(){const cutoff=Date.now()-120000;for(const [id,m]of members)if(m.at<cutoff)members.delete(id);return[...members.values()].filter(m=>m.mode===payload.mode);}
 async function start(value){payload=clean(value);if(server)return info();token=crypto.randomBytes(24).toString('hex');server=http.createServer(async(req,res)=>{
  const url=new URL(req.url,'http://localhost'),prefix='/'+token;if(!(url.pathname===prefix||url.pathname.startsWith(prefix+'/'))){res.writeHead(403);res.end('Private pairing link required');return;}res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Cache-Control','no-store');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; object-src 'none'; frame-ancestors 'none'");const suffix=url.pathname.slice(prefix.length);
  if(suffix==='/state'){res.setHeader('Content-Type','application/json');const ref=JSON.parse(fs.readFileSync(path.join(__dirname,'data/reference.json'),'utf8'));res.end(JSON.stringify({host:payload,members:current(),maps:ref.maps,levels:ref.levels}));return;}
  if(suffix==='/member'&&req.method==='POST'){if(req.headers.origin&&req.headers.origin!==`http://${req.headers.host}`){res.writeHead(403);res.end();return;}let body='';try{for await(const chunk of req){body+=chunk;if(body.length>150000)throw Error('Update too large');}const value=JSON.parse(body),id=String(value.memberId||'').slice(0,60);if(!/^[a-zA-Z0-9-]{8,60}$/.test(id))throw Error('Invalid member ID');if(members.size>=10&&!members.has(id))throw Error('Squad is full');members.set(id,{...clean(value),id});onMembers?.(current());res.setHeader('Content-Type','application/json');res.end(JSON.stringify({members:current()}));}catch(e){res.writeHead(400);res.end(e.message);}return;}
  let file;if(suffix===''||suffix==='/')file=path.join(__dirname,'phone.html');else if(suffix==='/phone.js'||suffix==='/phone.css')file=path.join(__dirname,suffix.slice(1));else if(suffix.startsWith('/maps/')){let relative;try{relative=decodeURIComponent(suffix.slice(6));}catch{res.writeHead(400);res.end();return;}const base=path.resolve(__dirname,'maps');file=path.resolve(base,relative);if(!file.startsWith(base+path.sep)||!['.png','.svg'].includes(path.extname(file))){res.writeHead(403);res.end();return;}}else{res.writeHead(404);res.end();return;}
  fs.readFile(file,(e,b)=>{if(e){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',{'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml'}[path.extname(file)]);res.end(b);});
 });await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'0.0.0.0',resolve);});port=server.address().port;return info();}
 function info(){return{urls:server?Object.values(os.networkInterfaces()).flat().filter(n=>n.family==='IPv4'&&!n.internal).map(n=>`http://${n.address}:${port}/${token}/`):[],port,token:server?token:null};}
 return{start,info,update:value=>{payload=clean(value);return current();},stop:()=>{server?.close();server=null;token=null;members.clear();onMembers?.([]);},join:async(url,value)=>{const u=new URL(url);if(u.protocol!=='http:'||!/^\/(?:[a-f0-9]{48})\/?$/.test(u.pathname)||!(/^(?:192\.168\.|10\.|172\.(?:1[6-9]|2\d|3[01])\.|127\.)/.test(u.hostname)))throw Error('Use a private-network Companion pairing link.');u.pathname=u.pathname.replace(/\/$/,'')+'/member';const result=await fetch(u,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...clean(value),memberId:value.memberId}),signal:AbortSignal.timeout(5000)});if(!result.ok)throw Error('Unable to join squad: '+await result.text());return result.json();}};
};
