'use strict';
(()=>{
 let busy=false,lastRun=0;
 const labels={discovery:'Local folders',mode:'Game mode',progress:'Quest & raid progress',hideout:'Hideout & inventory',position:'Screenshot position',data:'Community data',controls:'Game keybinds'};
 function card(){const r=state.settings.lastSync;return `<section class="card sync-settings"><h2>One-button sync</h2><p>Detects local folders, your last logged game mode and recognized quest/raid events. Refreshes quest/hideout requirements, recipes, maps and prices.</p><div class="toolbar"><button data-sync-action="run">Sync now</button><button data-sync-action="report">Last result</button></div><label><input id="sync-follow" type="checkbox" ${state.settings.syncFollow?'checked':''}> Keep detected sources synchronized</label><p class="subtext">When enabled: read new client-log/screenshot filenames as they arrive and refresh community data every 10 minutes while this app is open. No game input, memory access or account login. ${r?'Last checked '+new Date(r.at).toLocaleString()+'.':''}</p></section>`;}
 function report(result=state.settings.lastSync){let dialog=document.querySelector('#sync-report');if(!dialog){dialog=document.createElement('dialog');dialog.id='sync-report';document.body.append(dialog);}dialog.innerHTML=`<div class="section-head"><h2>Sync result</h2><button data-sync-action="close">Close</button></div>${result?`<p class="subtext">${new Date(result.at).toLocaleString()} · ${escape(result.mode)} · ${escape(result.profile||profile().name)}</p><div class="sync-results">${result.steps.map(s=>`<div class="sync-result ${s.status}"><b>${labels[s.id]||escape(s.id)}</b><span>${escape(s.detail)}</span><small>${{updated:'Updated',ready:'Detected',attention:'No automatic change',unavailable:'Not exposed',error:'Needs attention'}[s.status]||'Checked'}</small></div>`).join('')}</div><p class="subtext">Sync only applies identifiable source records. Built hideout levels and inventory cannot currently be reconstructed from the verified local sources; your entries stay intact.</p>`:'<p>Use Sync now to detect available sources.</p>'}`;TCArt.decorate(dialog,page,profile());if(!dialog.open)dialog.showModal();}
 function enhance(){const header=document.querySelector('.header-actions');if(!overlay&&header&&!header.querySelector('[data-sync-action=run]'))header.insertAdjacentHTML('afterbegin','<button class="primary" data-sync-action="run" title="Detect local sources and sync everything available">Sync</button>');document.querySelectorAll('[data-sync-action=run]').forEach(b=>{b.disabled=busy;if(b.closest('.header-actions')){b.innerHTML=TCArt.icon('refresh')+(busy?'Syncing…':'Sync');b.classList.add('art-button');}});document.querySelectorAll('#profile-select,#profile-mode,[data-action=profile-save],[data-action=profile-new]').forEach(n=>n.disabled=busy);if(page==='settings'&&!document.querySelector('.sync-settings'))document.querySelector('.settings-grid')?.insertAdjacentHTML('afterbegin',card());TCArt.decorate(document,page,profile());}
 async function run({background=false}={}){if(busy)return;busy=true;enhance();try{
   let result;if(window.desktop?.syncAll)result=await window.desktop.syncAll(profile().mode,{background});else{const r=await fetch('/api/sync?mode='+profile().mode,{method:'POST'}),j=await r.json();result={at:Date.now(),mode:profile().mode,steps:[{id:'data',status:r.ok?'updated':'error',detail:r.ok?'Community data refreshed.':j.error||'Refresh failed.'},{id:'progress',status:'unavailable',detail:'Automatic local progress sync requires the desktop app.'},{id:'hideout',status:'unavailable',detail:'Built levels are not exposed by the community database.'}],events:[],sources:{}};}
   if(!background&&result.detectedMode&&result.mode!==profile().mode){const matches=state.profiles.filter(p=>p.mode===result.mode);let target=matches.length===1?matches[0]:null;if(!matches.length){target=blankProfile(profile().name,result.mode);state.profiles.push(target);}if(target)state.active=target.id;else{const step=result.steps.find(s=>s.id==='mode');if(step){step.status='attention';step.detail='Multiple profiles match the detected mode. Select your intended profile and Sync again; progress stays queued.';}}}
   const p=profile(),sources=result.sources||{};if(sources.logsFolder)state.settings.logsFolder=sources.logsFolder;if(sources.screenshotFolder)state.settings.screenshotFolder=sources.screenshotFolder;state.settings.logProfile=p.id;
   if(!background&&state.settings.syncFollow===undefined)state.settings.syncFollow=true;
   state.settings.logSync=Boolean(state.settings.syncFollow&&sources.logsFolder);state.settings.autoPosition=Boolean(state.settings.syncFollow&&sources.screenshotFolder);
   await loadData();
   const applied=await receive(result.events||[]),progress=result.steps.find(s=>s.id==='progress');if(progress&&progress.status!=='error'&&progress.status!=='unavailable'){progress.status=applied.changes?'updated':'attention';progress.detail=(applied.changes?`${applied.changes} recognized changes applied to this profile.`:'No new recognized quest/raid changes for this profile.')+(applied.pending?` ${applied.pending} records retained for another mode or unrecognized source.`:'');}
   const shot=result.screenshot,posStep=result.steps.find(s=>s.id==='position');if(shot?.mapHint&&Date.now()-shot.at<86400000&&shot.at>(p.location?.at||0)){const projected=TarkovCore.worldToMap(shot.position,data.maps[shot.mapHint]);if(projected.inBounds){p.map=shot.mapHint;updatePosition(shot.position,shot.name);p.location.at=shot.at;p.lastSyncedScreenshot=shot.name;if(posStep){posStep.status='updated';posStep.detail='Latest explicitly labeled map position imported.';}}}else if(shot?.mapHint&&posStep){posStep.status='attention';posStep.detail='Screenshot is older than your current position or more than a day old; position preserved.';}
   state.settings.lastSync={at:result.at,mode:p.mode,profile:p.name,steps:result.steps};lastRun=Date.now();save();render();if(!background)report(state.settings.lastSync);
  }catch(e){toast('Sync failed: '+e.message);}finally{lastRun=Date.now();busy=false;enhance();}}
 async function receive(events){const p=profile();if(state.settings.logProfile&&state.settings.logProfile!==p.id)return{changes:0,pending:events.length};const eligible=(events||[]).filter(e=>e.mode===p.mode&&(e.type==='quest'?data.tasks.some(t=>t.id===e.id):e.type==='raid'&&Object.entries(data.maps).some(([id,m])=>id===e.map||m.locale.en.toLowerCase()===String(e.map).toLowerCase())));const changes=applyLogEvents(eligible,{quiet:true});save();if(window.desktop){await window.desktop.saveState(state);const keys=eligible.map(e=>e.dedupeKey).filter(Boolean);for(let i=0;i<keys.length;i+=10000)await window.desktop.ackSync(keys.slice(i,i+10000));}return{changes,pending:events.length-eligible.length};}
 async function selected(){if(!state.settings.syncFollow||!window.desktop)return;state.settings.logProfile=profile().id;await receive(await window.desktop.pendingSync());}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-sync-action]');if(!b)return;switch(b.dataset.syncAction){case'run':run();break;case'report':report();break;case'close':document.querySelector('#sync-report')?.close();break;}});
 document.addEventListener('change',e=>{if(e.target.id==='sync-follow'){state.settings.syncFollow=e.target.checked;state.settings.logSync=Boolean(e.target.checked&&state.settings.logsFolder);state.settings.autoPosition=Boolean(e.target.checked&&state.settings.screenshotFolder);save();}});
 setInterval(()=>{if(!overlay&&typeof state!=='undefined'&&state?.settings.syncFollow&&Date.now()-Math.max(lastRun,state.settings.lastSync?.at||0)>600000)run({background:true});},30000);
 function position(result){const stem=' '+result.name.toLowerCase().replace(/[^a-z0-9]+/g,' ')+' ',hints=Object.entries(data.maps).filter(([id,m])=>[id,m.locale.en].some(n=>stem.includes(' '+String(n).toLowerCase().replace(/[^a-z0-9]+/g,' ')+' ')));if(hints.length!==1){toast('Screenshot detected, but its map is unknown. Select your map and use Import position.');return;}const map=hints[0][0],loc=TarkovCore.worldToMap(result.position,data.maps[map]);if(!loc.inBounds){toast('Screenshot coordinates do not match the labeled map. Position preserved.');return;}profile().map=map;updatePosition(result.position,result.name);}
 window.SyncUI={enhance,run,position,receive,selected};
})();
